---
ansible_host: 10.150.1.10
ansible_user: ansible
ansible_ssh_private_key_file: ~/.ssh/vps-ansible
# ansible_python_interpreter: /usr/bin/python3

staging: true
quentin_bonnet_software_dns_name: bonnet-software.vps-staging.home
ghost_url: https://ghost.vps-staging.home
